switch_ports: Unset adaptive policy on port deletion
If `adaptive_policy_group_id` is set in a port,
deleting the adaptive policy group after the port from the list fails:
```
Error: Client Error
Failed to delete object (DELETE), got error: HTTP Request failed: StatusCode
400, {"errors":["This adaptive policy group is in use on the following ports
in the netascode-network-01 - switch network: switch
netascode-access-switch-01, port 7; switch netascode-access-switch-01, port
10; switch netascode-access-switch-01, port 11; switch
netascode-access-switch-01, port 12; switch netascode-access-switch-01, port
5. Please remove the policy from these ports before deleting the group."]}
```

This was already fixed in `switch_port` (the non-bulk resource)
by setting `"adaptivePolicyGroupId": null`
in 633bcffab77e006ac328a78fd30f8dd2ba64516d
by overriding the generated code manually
instead of using `destroy_value` to generate it.
The manual change was not copied when the bulk resource was added.

The change had to be done manually due to API behavior:
https://github.com/CiscoDevNet/terraform-provider-meraki/pull/89/commits/633bcffab77e006ac328a78fd30f8dd2ba64516d
> Always sending `"adaptivePolicyGroupId": null` on deletion
> can fail with "Adaptive Policy is not enabled in this network".
> That refers to meraki_organization_adaptive_policy_settings resource
> having adaptive policy enabled for this network.
>
> Only send that if `adaptive_policy_group_id` was previously set
> (which would mean that adaptive policy
> would have been enabled on the network -
> we can't check that directly here).